parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     craftycomponents
    database_user:     root
    database_password: 82minuty

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            sadfsadfsgfsdfg546dsfgdsf