<?php

namespace FWM\CraftyComponentsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VerionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionsRepository extends EntityRepository
{
}